config/routes.rb
Blogament::Engine.routes.draw do
  get "/tags/:tag", to: "posts#index", as: :tag

  root to: "posts#index"

  resources :posts do
    resources :comments
  end

end

app/models/blogament/comment.rb
module Blogament
  class Comment < ActiveRecord::Base
    belongs_to :posts
    belongs_to :author, class_name: "::#{Blogament.author_class}"

    def author_gravatar_url
      stripped_email = self.author.email.strip
      downcased_email = stripped_email.downcase
      hash = Digest::MD5.hexdigest(downcased_email)
      "http://gravatar.com/avatar/#{hash}"
    end

  end
end

app/models/blogament/post.rb
module Blogament
  class Post < ActiveRecord::Base
    searchkick autocomplete: ['title']
    mount_uploader :image, ImageUploader
    process_in_background :image
    acts_as_taggable

    has_many :comments
    belongs_to :author, class_name: "::#{Blogament.author_class}"
  end
end

app/controllers/blogament/application_controller.rb
module Blogament
  class ApplicationController < ActionController::Base
  end
end

app/controllers/blogament/comments_controller.rb
#require_dependency "blogament/application_controller"

module Blogament
  class CommentsController < ApplicationController
    before_action :can_user_comment?, only: [:create]

    def create
      @post = Post.find(params[:post_id])
      @comment = @post.comments.new(comment_params)
      @comment.author_id = current_user.id

      if @post.save
        flash[:notice] = "Your comment's been added."
      end
      redirect_to @post
    end

    private
      def comment_params
        params.require(:comment).permit(:text, :author_id)
      end

      def can_user_comment?
        redirect_to root_url unless current_user
      end

  end
end

app/controllers/blogament/posts_controller.rb
module Blogament
  class PostsController < ApplicationController
    before_action :can_user_create_posts?, only: [:new, :edit, :update, :destroy]
    before_action :correct_user,           only: [:edit, :update, :destroy]
    before_action :set_post,               only: [:show, :edit, :update, :destroy]

    # GET /posts
    def index
      if params[:tag]
        @posts = Post.tagged_with(params[:tag])
      elsif query = params[:query]
        @search = Blogament::Post.search(query, misspellings: {distance: 4}, suggest: true)
        @posts  = Blogament::Post.where(id: @search.map(&:id))
      else
        @posts = Post.all
      end
    end

    # GET /posts/1
    def show
    end

    # GET /posts/new
    def new
      @post = Post.new
    end

    # GET /posts/1/edit
    def edit
    end

    # POST /posts
    def create
      @post = Post.new(post_params)
      @post.author_id = current_user.id

      if @post.save
        flash[:success] = "Your blog post's been published."
        redirect_to posts_path
      else
        render action: 'new'
      end
    end

    # PATCH/PUT /posts/1
    def update
      if @post.update(post_params)
        flash[:success] = "Your post's been updated."
        redirect_to posts_path
      else
        render action: 'edit'
      end
    end

    # DELETE /posts/1
    def destroy
      @post.destroy
      flash[:success] = "Post was successfully destroyed."
      redirect_to posts_url
    end

    private
      def can_user_create_posts?
        redirect_to root_url unless current_user && current_user.can_blog?
      end

      def correct_user
        @post = Post.find(params[:id])
        redirect_to root_url if @post.author_id != current_user.id
      end

      def set_post
        @post = Post.find(params[:id])
      end

      def post_params
        params.require(:post).permit(:title, :text, :image, :tag_list)
      end
  end
end

app/helpers/blogament/application_helper.rb
module Blogament
  module ApplicationHelper
  end
end

app/helpers/blogament/comments_helper.rb
module Blogament
  module CommentsHelper
  end
end

app/helpers/blogament/posts_helper.rb
module Blogament
  module PostsHelper
  end
end

app/views/blogament/comments/_comment.html.erb
<p class="comment">
<%= image_tag comment.author_gravatar_url %>
<%= comment.text %>
</p>

app/views/blogament/comments/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= form_for [@post, @post.comments.build], class: "form-horizontal" do |f| %>
      <fieldset>
        <legend>New Comment</legend>

          <div class="field form-group">
            <%= f.label :text, hidden: true %><br>
            <div class="col-lg-12">
              <%= f.text_area :text, class: "form-control input-lg" %>
            </div>
          </div>

          <div class="actions form-group">
            <div class="col-lg-12">
              <br>
              <%= f.submit class: "btn btn-success" %>
            </div>
          </div>

        <% end %>
      </fieldset>
    </form>
  </div>
</div>

app/views/blogament/posts/_form.html.erb
<div class="row">

  <div class="field form-group s3">
  <%= s3_uploader_form callback_url: @post_url, callback_param: "post[image_url]", id: "s3-uploader" do %>
    <%= file_field_tag :file, multiple: true %>
  <% end %>
  </div>

  <%= form_for @post, :html => {class: "form-horizontal", :multipart => true} do |f| %>
    <fieldset>
      <legend></legend>
        <% if @post.errors.any? %>
          <div id="error_explanation notice">
            <div class="alert alert-temp fade in alert-error">
              <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
            </div>
            <ul class="unstyled">
            <% @post.errors.full_messages.each do |msg| %>
              <li class="alert alert-error"><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field form-group">
          <%= f.label :title, class: "col-lg-1 control-label input-lg" %><br>
          <div class="col-lg-11">
            <%= f.text_field :title, class: "form-control input-lg" %>
          </div>
        </div>

        <div class="field form-group">
          <%= f.label :tag_list, class: "col-lg-1 control-label input-lg" %><br>
          <div class="col-lg-11">
            <%= f.text_field :tag_list, { :placeholder => "Tags separated by commas", class: "form-control input-lg" } %>
          </div>
        </div>

        <div class="field form-group hidden">
          <%= f.label :image, class: "col-lg-1 control-label input-lg" %><br>
          <div class="col-lg-11">
            <%= f.text_field :image, class: "input-lg" %>
          </div>
        </div>

        <div class="progress progress-striped active hidden">
          <div class="progress-bar progress-bar-success" style="width: 0%"></div>
        </div>

        <div class="field form-group">
          <%= f.label :text, hidden: true, class: "col-lg-1 control-label input-lg" %><br>
          <div class="col-lg-12">
            <%= f.text_area :text, :id => "tinymce4", :rel => "tinymce", :rows => 10, :cols => 40 %>
          </div>
        </div>

        <div class="actions form-group">
          <div class="col-lg-12">
            <%= f.submit class: "btn btn-success" %>
          </div>
        </div>
      <% end %>

  </div>

app/views/blogament/posts/edit.html.erb
<div class="row">
  <div class="col-lg-6">
    <h1>Edit</h1>
  </div>

  <div class="col-lg-6">
    <div class="btn-group pull-right">
      <%= link_to 'Show', @post, class: "btn btn-default" %>
      <%= link_to 'Back', posts_path, class: "btn btn-default" %>
    </div>
  </div>
</div>

  <%= render 'form' %>

app/views/blogament/posts/index.html.erb
<div class="row">
  <h1>Blogs</h1>
  <br />

  <%= form_tag posts_path, method: "get" do %>
    <div class="form-group col-lg-12">
      <div class="input-group input-lg">
        <span class="input-group-addon"></span>
          <%= text_field_tag :query, params[:query], placeholder: "What are you searching for?", class: "form-control" %>
        <span class="input-group-btn">
         <%= submit_tag 'Search', class: "btn btn-success" %>
        </span>
      </div>
    </div>
  <% end %>

  <div class="col-lg-12">

    <% @posts.each do |post| %>
      <div class="panel panel-info animated fadeInDown">
        <div class="panel-heading">
          <h3 class="panel-title">
            <%= post.title %>
          </h3>
        </div>
        <div class="panel-body">
          <blockquote>
            <p class="truncate"><%= strip_tags(post.text).truncate(40) %></p>
          </blockquote>

        <%= raw post.tags.map(&:name).map { |t| link_to t, tag_path(t), class: "label label-default" }.join(' ') %>

        </div>
        <div class="panel-footer">
          <small><%= post.author.by_line %></small>
          <div class="pull-right">
            <%= link_to 'Full Post', post, class: "btn btn-info" %>
          </div>
          <div class="clear"></div>
        </div>
      </div>
    <% end %>

  </div>

  <br>

  <% if current_user %>
    <%= link_to 'New Post', new_post_path, class: "btn btn-success" %>
  <% end %>
</div>
<br>

app/views/blogament/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/blogament/posts/show.html.erb
<div class="row">

  <div class="col-lg-12 pull-right">
    <div class="btn-group pull-right">
      <% if current_user && @post.author == current_user %>
        <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-default" %>
        <%= link_to "Delete", @post,
                              class: "btn btn-default",
                              method: :delete,
                              data: { confirm: "You sure?" },
                              title: @post.title %>
        <%= link_to 'Back', posts_path, class: "btn btn-default" %>
      <% end %>
    </div>
  </div>

  <div class="col-lg-12 blog-container">
    <div class="jumbotron">
      <h1 class="animated fadeInRight"><%= @post.title %></h1>

      <div id="tags">
        <%= raw @post.tags.map(&:name).map { |t| link_to t, tag_path(t), class: "label label-info" }.join(' ') %>
      </div>

      <div class="blog-img">
        <%= image_tag @post.image.url(:main) %>
      </div>
      <p>
        <%= raw @post.text %>
      </p>
      <hr>
      <small> &bull; <%= @post.author.by_line %></small>
      <div class="clear"></div>
      <div>
        <%= social_share_button_tag(@post.title) %>
      </div>
    </div>
  </div>

<div class="row">
  <div class="col-lg-12">

  <h3>Comments</h3>
    <%= render @post.comments %>
  <hr>
    <% if current_user %>
      <%= render "blogament/comments/form" %>
    <% else %>
      <%= link_to 'Login to Comment', main_app.root_path, class: "btn btn-default" %>
    <% end %>
  <br>
  <br>
  </div>
</div>

app/views/layouts/blogament/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogament</title>
  <%= stylesheet_link_tag    "blogament/application", media: "all" %>
  <%= javascript_include_tag "blogament/application" %>
  <%= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.9.3/typeahead.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-default">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Home", main_app.root_path, class: "navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Posts", posts_path %></li>
      </ul>
      <%= form_tag posts_path, method: "get", class: "navbar-form navbar-right" do %>
        <div class="form-group">
          <div class="input-group">
            <span class="input-group-addon"></span>
              <%= text_field_tag :query, params[:query], placeholder: "Search", class: "form-control" %>
            <span class="input-group-btn">
             <%= submit_tag 'Search', class: "btn btn-default" %>
            </span>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="container">

  <div id="notice">
    <% flash.each do |key, value| %>
      <div class="alert-temp alert fade in alert-<%= key %>"><%= value %></div>
    <% end %>
  </div>

    <%= yield %>

  </div>

  <%= tinymce %>
  <script id="template-upload" type="text/x-tmpl">
    <div id="file-{%=o.unique_id%}" class="upload">
      {%=o.name%}
      <div class="progress"><div class="bar" style="width: 0%"></div></div>
    </div>
  </script>

  <%= javascript_tag do %>
    $('#s3-uploader').bind('s3_upload_complete', function(e) {
      $("#s3-uploader").hide();
      $(".s3").text("Your file's been uploaded.");
    });
  <% end %>

  <%= javascript_tag do %>
    $('#s3-uploader').bind("s3_upload_complete", function(e, content) {
      $('input#post_image.input-lg').val(content.url);
    });
  <% end %>

  </body>
</html>